### ISSUE TITLE
[Feature Request] Scrape Petitions

### ISSUE THREAD

**Issue by KipCrossing** [OpenGovAus/Aus-Bills#35]
Need to investigate how viable it is to scrape petitions such as:

https://www.aph.gov.au/petition_list

Would be nice to include this in ausbills.

**Comment by KipCrossing** [comment]
This one may also be out of scope? perhaps a new repo?

**Comment by king-millez** [comment]
> 
> 
> This one may also be out of scope? perhaps a new repo?

Agreed, petitions offer interactivity too (with signing features), definitely material for a different repo.
